name: ituapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_xlider: ^3.5.0
  table_calendar: ^3.0.9
  firebase_storage: ^11.4.1
  firebase_database: ^10.3.3
  google_maps_flutter: ^2.5.0
  file_picker: ^6.1.1
  flutter_calendar_carousel: ^2.4.2
  firebase_auth: ^4.12.1
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/user.png

