// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rgQCtgpqt7GZu7o8Ubi7Dy8Rk7SkZ6I',
    appId: '1:483894081462:web:618fa7e26b922892ed7317',
    messagingSenderId: '483894081462',
    projectId: 'itu-6f4f6',
    authDomain: 'itu-6f4f6.firebaseapp.com',
    storageBucket: 'itu-6f4f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU45Hhd0X7i-5Lf0sxGQf6E_0Ij1TqVXM',
    appId: '1:483894081462:android:d45a1303fcfd34e3ed7317',
    messagingSenderId: '483894081462',
    projectId: 'itu-6f4f6',
    storageBucket: 'itu-6f4f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgH_J_iBV5m45dHLxCvwsuwzP12JGCniE',
    appId: '1:483894081462:ios:254d7ac78a00d8d0ed7317',
    messagingSenderId: '483894081462',
    projectId: 'itu-6f4f6',
    storageBucket: 'itu-6f4f6.appspot.com',
    iosBundleId: 'com.example.ituapp',
  );
}
